### ISSUE TITLE
Wrong language indication

### ISSUE THREAD

**Issue by GeneralGeki** [d120/pyophase#126] opened 2017-01-26 15:00 UTC
As seen in the screenshot the site _https://d120.de/ophase/master-dss/_ is written in english, although the "switch language" button shows "DE".

![pyophasesprachfehler](https://cloud.githubusercontent.com/assets/10200056/22335650/cee525c0-e3df-11e6-9b07-da41945c971d.png)

**Comment by ckleemann** [comment] 2017-01-26 15:20
Actually this is not a bug it is a feature since DSS is an English master program.

**Comment by GeneralGeki** [comment] 2017-01-26 15:24
But shouldn't the language indicator automatically switch to EN?

**Comment by ckleemann** [comment] 2017-01-26 16:14
Ah okay now i got your point. No the i18n Model is different: There is a default language for the entire Django Project, which is DE in pyOphase, if a translation is available it gets translated to English. If no translation is available the language switch dose not have any effect.

But for this page the text is declared to be German but it is English and there is no translation available. So the "right" way to fix this would be: Translate the text to German and maintain the German and English version. German in the view and English in the language file. But since we actually do not need a German version for this view it is simpler to maintain only an English version and stay as it is.

**Comment by ckleemann** [comment] 2017-01-26 16:16
Maybe we could at a note for the German version that this information are only available in English.

**Comment by bhaettasch** [comment] 2017-07-23 14:04
As we even integrated code to change language for individual content boxes in the website component, I doubt that adjusting everything according to the language switcher is necessary. I will close this issue now, please give further arguments to reopen it.

**Closed by bhaettasch** 2017-07-23 14:04 UTC
Labels: text
