### ISSUE TITLE
Editing of the landing page

### ISSUE THREAD

**Issue by GeneralGeki** [d120/pyophase#116] opened 2016-12-19 17:45 UTC
The landing page must be editable from the admin interface.
For example - and this is a request - the landing page must be adjustable for the Ophase in the summer term.
Also, the admin must be able to edit the page if there is no preperation course (maths and programming).

**Comment by schroedingersZombie** [comment] 2017-02-06 10:09
Should be fixed with b22529d see also #129

**Comment by bhaettasch** [comment] 2017-04-06 15:37
Maybe we could replace the whole website component with either an API or some kind of widgets that can be included/displayed on the normale homepage?

**Comment by exploide** [comment] 2017-04-06 15:43
If pyophase would provide an API, django CMS could incorporate content via a simple self written "integrator" app. Shouldn't be that hard. If CMS like content editing is desired, probably this is relevant: http://docs.django-cms.org/en/release-3.4.x/how_to/placeholders.html

**Comment by bhaettasch** [comment] 2017-07-26 16:25
Duplicate of #90 -- but as this issue contains more proposed solutions, I will close the other one.

**Comment by ckleemann** [comment] 2021-02-07 23:30
Wont Fix. The content e.g. website app is deprecated and will be removed as requested in #463

**Closed by ckleemann** 2021-02-07 23:30 UTC
Labels: enhancement, meta, ux
