### ISSUE TITLE
Helper choice Matrix

### ISSUE THREAD

**Issue by ckleemann** [d120/pyophase#27] opened 2015-09-07 13:42 UTC
A Matrix which shows which shows Helpers as one dimension and the jobs as the second dimension. This could be implemented as html view or as ods export.

**Comment by exploide** [comment] 2015-09-07 13:53
probably related to or duplicate of #18
feel free to do something useful :stuck_out_tongue:

**Closed** 2015-09-08 17:20 UTC
Labels: feature
