### ISSUE TITLE
add categories for orgajobs

### ISSUE THREAD

**Issue by chriswars** [d120/pyophase#70] opened 2016-04-28 21:18 UTC
add a category selectfield for orgajobs (e.g. bachelor only, master only, general..)
- adminpage filter
- group the list of job explanations
- if possible: reorder the multipleselect field of the signup form: categories as <optgroup>s, jobs as <option>

**Comment by exploide** [comment] 2016-07-12 11:02
duplicate of #56

**Closed by exploide** 2016-07-12 11:02 UTC
Labels: enhancement, feature
